import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import Sidebar from '../components/Sidebar'
import Table from '../components/Table'
import React from 'react';
import CustomerEdit from '../components/CustomerEdit'
import { DummyTableDataRow } from '../common/constant'

const Home: NextPage = () => {
  const [openCustomerEdit, setOpenCustomerEdit] = React.useState(false);

  function getDummyCustomerData(): any[] {
    const dummyArr = [];
    for (var i = 0; i < 17; i++) {
      dummyArr.push(DummyTableDataRow);
    }
    return dummyArr;
  }

  return (
    <div>
      <Head>
        <title>Customer - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout title={'Customer'} children={<>
          <Table headers={['Equipment ID', 'Customer', 'Outlet', 'Equipment Type', 'Equipment Name', 'Valid as Of']} data={getDummyCustomerData()} handleAddNew={() => setOpenCustomerEdit(true)} handleEdit={() => setOpenCustomerEdit(true)} handleDelete={() => setOpenCustomerEdit(true)} rightSideElements={[]} leftSideElements={[]} buttonText={'+ Add New Customer'} />
          <CustomerEdit openCustomerEdit={openCustomerEdit} setOpenCustomerEdit={setOpenCustomerEdit} /></>} />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
        </a>
      </footer>
    </div>
  )
}

export default Home
