import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout'
import Table from '../components/Table'
import React from 'react';
import OutletEdit from '../components/OutletEdit';
import CustomizedInput from '../components/CustomizedInput';
import TableOptionField from '../components/TableOptionField';
import { DummyOutletDataRow } from '../common/constant';

const Outlets: NextPage = () => {
  const [openOutletEdit, setOpenOutletEdit] = React.useState(false);

  function getDummyOutletData(): any[] {
    const dummyArr = [];
    for (var i = 0; i < 17; i++) {
      dummyArr.push(DummyOutletDataRow);
    }
    return dummyArr;
  }
  return (
    <div>
      <Head>
        <title>Outlet - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout title={'Outlet'} children={<>
          <Table
            headers={['Outlet ID', 'Customer', 'Outlet Name', 'Tariff Rate', 'Date of Tariff', 'Share of Savings']}
            data={getDummyOutletData()}
            rightSideElements={[
              <TableOptionField label={'Outlet'} data={['KFC Indonesia']} />
            ]}
            handleAddNew={() => {
              setOpenOutletEdit(true);
            }} handleEdit={() => setOpenOutletEdit(true)} handleDelete={() => setOpenOutletEdit(true)} buttonText={"+ Add New Outlet"} leftSideElements={[]} />
          <OutletEdit openOutletEdit={openOutletEdit} setOpenOutletEdit={setOpenOutletEdit} /></>} />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
        </a>
      </footer>
    </div>
  )
}

export default Outlets
